In [1]:
import pandas as pd
df = pd.read_csv('./1668008312256-AR6_Scenarios_Database_World_v1.1.csv/AR6_Scenarios_Database_World_v1.1.csv')
meta = pd.read_excel('./1668008312256-AR6_Scenarios_Database_World_v1.1.csv/AR6_Scenarios_Database_metadata_indicators_v1.1.xlsx',sheet_name = 'meta')

In [2]:
meta.head()

,Model,Scenario,Category,Category_name,Category_subset,Subset_Ch4,Category_Vetting_historical,IMP_marker,Literature Reference (if applicable),Policy_category,...,P67 peak warming (FaIRv1.6.2),Median warming in 2100 (FaIRv1.6.2),Median year of peak warming (FaIRv1.6.2),Exceedance Probability 1.5C (FaIRv1.6.2),Exceedance Probability 2.0C (FaIRv1.6.2),Exceedance Probability 3.0C (FaIRv1.6.2),IMP_color_rgb,IMP_color_hex,Category_color_rgb,Category_color_hex
0,AIM/CGE 2.0,ADVANCE_2020_1.5C-2100,failed-vetting,failed-vetting,C1a_NZGHGs,Limit to 1.5C (>50%) no or low OS immediate 20...,failed_Vetting_historical_failed-vetting,non-IMP,https://doi.org/10.1038/s41558-018-0198-6,P2a,...,1.501157,1.056861,2037,0.332588,0.009388,0,NaN,NaN,"151, 206, 228",97CEE4
1,AIM/CGE 2.0,ADVANCE_2020_Med2C,failed-vetting,failed-vetting,C4,NaN,failed_Vetting_historical_failed-vetting,non-IMP,https://doi.org/10.1038/s41558-018-0198-6,P2a,...,1.92688,1.772975,2100,0.820742,0.26017,0.004023,NaN,NaN,"167, 198, 130",A7C682
2,AIM/CGE 2.0,ADVANCE_2020_WB2C,failed-vetting,failed-vetting,C1b_+veGHGs,Limit to 1.5C (>50%) no or low OS immediate 20...,failed_Vetting_historical_failed-vetting,non-IMP,https://doi.org/10.1038/s41558-018-0198-6,P2a,...,1.565292,1.384028,2050,0.426017,0.035762,0.000447,NaN,NaN,"151, 206, 228",97CEE4
3,AIM/CGE 2.0,ADVANCE_2030_Med2C,failed-vetting,failed-vetting,C4,NaN,failed_Vetting_historical_failed-vetting,non-IMP,https://doi.org/10.1038/s41558-018-0198-6,P3b,...,2.043335,1.882453,2100,0.907912,0.374162,0.008494,NaN,NaN,"167, 198, 130",A7C682
4,AIM/CGE 2.0,ADVANCE_2030_Price1.5C,failed-vetting,failed-vetting,C2,Limit 2C (>67%) or return to 1.5C (>50%) after...,failed_Vetting_historical_failed-vetting,non-IMP,https://doi.org/10.1038/s41558-018-0198-6,P3b,...,1.705307,1.37244,2039,0.646401,0.071524,0.000447,NaN,NaN,"119, 134, 99",778663

In [3]:
year_columns = [str(x) for x in list(range(2005,2101,5))] # At five-year intervals, take the values of the variables for the period 2005-2100
variable = 'AR6 climate diagnostics|Infilled|Emissions|Kyoto Gases (AR6-GWP100)'
df_sub = df.loc[df.Variable == variable,['Model','Scenario']+year_columns]#"df_sub" contains the values of the variables during 2005-2100 and their corresponding Models and Scenarios
df_sub.head()

,Model,Scenario,2005,2010,2015,2020,2025,2030,2035,2040,...,2055,2060,2065,2070,2075,2080,2085,2090,2095,2100
22,AIM/CGE 2.0,ADVANCE_2020_1.5C-2100,NaN,NaN,54308.531541,57470.892291,38167.555805,26290.424130,16970.822806,9066.273495,...,-557.517747,-1886.532544,-2863.000992,-3920.303818,-4420.858863,-4371.943774,-4898.313273,-5775.986184,-3490.493841,-3741.742137
213,AIM/CGE 2.0,ADVANCE_2020_Med2C,NaN,NaN,54308.531541,57422.374986,40021.485800,30867.222902,27797.530096,27886.401185,...,20763.980958,17811.631238,21804.336390,19949.591905,20126.684927,20794.962792,20146.207853,18430.726582,17419.746369,15800.991669
404,AIM/CGE 2.0,ADVANCE_2020_WB2C,NaN,NaN,54308.531541,57493.569284,39659.288319,29982.093653,20437.715471,17873.002595,...,9005.385212,5883.709647,6614.742131,6106.135664,6688.278814,7334.968280,6997.053795,5229.948041,4692.906502,3688.707680
595,AIM/CGE 2.0,ADVANCE_2030_Med2C,NaN,NaN,54308.531541,57642.224775,57448.854512,55522.237384,36177.858237,25177.537256,...,20557.575009,17150.133351,20365.037959,19728.094949,20158.440070,21677.286546,21541.066766,19497.108073,18906.836712,17777.768452
786,AIM/CGE 2.0,ADVANCE_2030_Price1.5C,NaN,NaN,54308.531541,57749.999442,57855.006245,55275.559952,22920.351508,15197.470438,...,3157.295312,2340.092482,2584.549965,1303.761107,2261.356724,2153.819483,2490.846015,1892.600524,4748.506653,4698.768181

In [4]:
data = df_sub.merge(meta.loc[:,['Model','Scenario','Category','Category_name']], on=['Model', 'Scenario'])#Extract the category corresponding to each scenario in the meta and merge it with df_sub

In [5]:
data.sample(5)

,Model,Scenario,2005,2010,2015,2020,2025,2030,2035,2040,...,2065,2070,2075,2080,2085,2090,2095,2100,Category,Category_name
838,MESSAGEix-GLOBIOM_1.1,EN_INDCi2030_3000_COV_NDCp,NaN,NaN,54308.531541,53956.859422,50901.102140,50769.464728,53795.116457,54146.310082,...,49220.775287,48034.236576,45749.110391,43460.642420,38182.970847,32905.257685,26071.507995,19237.765043,C6,C6: limit warming to 3Â°C (>50%)
1011,POLES ADVANCE,ADVANCE_2030_WB2C,NaN,NaN,54308.531541,58507.662709,58288.450138,53576.472596,39963.379821,28266.163236,...,5610.149470,3560.618459,1086.119822,-1110.603863,-2911.237184,-4808.880321,-5856.003980,-7356.481054,C2,C2: return warming to 1.5Â°C (>50%) after a hig...
18,AIM/CGE 2.0,EMF30_D_Frozen-EF,NaN,NaN,54308.531541,60016.853471,63857.071802,67666.708877,71027.840980,74362.868649,...,84011.020006,85554.631318,87049.671147,88533.481239,90536.266118,92538.907097,94382.177460,96225.447820,failed-vetting,failed-vetting
1505,TIAM-ECN 1.1,EN_NPi2020_800,NaN,NaN,54308.531541,52990.992844,42801.342997,32600.423643,29312.294758,26009.014095,...,8005.883627,7160.405101,7276.176642,7392.868555,7517.257884,7642.867436,7812.420617,7983.551570,C3,C3: limit warming to 2Â°C (>67%)
1002,MUSE 1.0,PR_NDC_PriceOnly,NaN,NaN,54308.531541,57086.507308,55381.164744,50940.746063,47410.171476,43077.429616,...,25564.676108,25748.494234,26196.283244,26607.843190,26849.990096,26587.400175,26701.344206,27011.843430,failed-vetting,failed-vetting

In [6]:
data.shape

(1703, 24)

In [7]:
#data.to_csv('co2_ts.csv',index = False)

## Imputation

In [8]:
data.isna().sum()#The proportion of missing data at each point in time

Model               0
Scenario            0
2005             1703
2010             1703
2015                0
2020                0
2025                0
2030                0
2035                0
2040                0
2045                0
2050                0
2055                0
2060                0
2065                0
2070                0
2075                0
2080                0
2085                0
2090                0
2095                0
2100                0
Category            0
Category_name       0
dtype: int64

In [9]:
columns_drop = [str(x) for x in range(2005,2100,10)]  #Only data for the period 2010-2100 will be retained (10-year interval).
data_input = data.drop(columns = columns_drop)
data_input.sample()

,Model,Scenario,2010,2020,2030,2040,2050,2060,2070,2080,2090,2100,Category,Category_name
454,GCAM 5.3,SSP4-DACCS-1p9-3pctHR,NaN,59391.256311,48117.218566,41170.123261,28840.581421,10961.293553,-4165.905995,-7663.077832,-9106.178993,-9755.06239,failed-vetting,failed-vetting

In [10]:
data_input.isna().sum()/data_input.shape[0]

Model            0.0
Scenario         0.0
2010             1.0
2020             0.0
2030             0.0
2040             0.0
2050             0.0
2060             0.0
2070             0.0
2080             0.0
2090             0.0
2100             0.0
Category         0.0
Category_name    0.0
dtype: float64

In [11]:
#Fill in the missing values with the mean of the corresponding year.
data_input[data_input.select_dtypes(include=['number']).columns] = data_input.select_dtypes(include=['number']).fillna( data_input.select_dtypes(include=['number']).mean())

In [12]:
data_input.isna().sum()/data_input.shape[0]

Model            0.0
Scenario         0.0
2010             1.0
2020             0.0
2030             0.0
2040             0.0
2050             0.0
2060             0.0
2070             0.0
2080             0.0
2090             0.0
2100             0.0
Category         0.0
Category_name    0.0
dtype: float64

In [13]:
data_input.head(5)

,Model,Scenario,2010,2020,2030,2040,2050,2060,2070,2080,2090,2100,Category,Category_name
0,AIM/CGE 2.0,ADVANCE_2020_1.5C-2100,NaN,57470.892291,26290.424130,9066.273495,2665.564762,-1886.532544,-3920.303818,-4371.943774,-5775.986184,-3741.742137,failed-vetting,failed-vetting
1,AIM/CGE 2.0,ADVANCE_2020_Med2C,NaN,57422.374986,30867.222902,27886.401185,25171.105549,17811.631238,19949.591905,20794.962792,18430.726582,15800.991669,failed-vetting,failed-vetting
2,AIM/CGE 2.0,ADVANCE_2020_WB2C,NaN,57493.569284,29982.093653,17873.002595,13228.775741,5883.709647,6106.135664,7334.968280,5229.948041,3688.707680,failed-vetting,failed-vetting
3,AIM/CGE 2.0,ADVANCE_2030_Med2C,NaN,57642.224775,55522.237384,25177.537256,21841.365421,17150.133351,19728.094949,21677.286546,19497.108073,17777.768452,failed-vetting,failed-vetting
4,AIM/CGE 2.0,ADVANCE_2030_Price1.5C,NaN,57749.999442,55275.559952,15197.470438,6297.397703,2340.092482,1303.761107,2153.819483,1892.600524,4698.768181,failed-vetting,failed-vetting

In [14]:
data_input.to_csv('Kyoto Gases.csv', index = False)